# -*- coding: utf-8 -*-
"""Python interview Lessons

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWqI0RscAak-M75pNvVF2VJi4DBhgL3_
"""

import pandas as pd
import random
from faker import Faker

fake = Faker()
event_types = ["view", "add_to_cart", "checkout", "purchase"]
categories = ["Electronics", "Clothing", "Home", "Books", "Sports"]
devices = ["mobile", "desktop", "tablet"]
locations = ["New York", "London", "Berlin", "Tokyo", "Sydney"]

data = []
event_id = 1

for user_id in range(1001, 1051):  # 50 users
    for _ in range(random.randint(3, 10)):  # random events per user
        session_id = f"S{user_id}{random.randint(1,5)}"
        product_id = random.randint(500, 700)
        category = random.choice(categories)
        price = round(random.uniform(10, 500), 2)
        event_type = random.choice(event_types)
        device = random.choice(devices)
        location = random.choice(locations)
        event_time = fake.date_time_this_month()

        data.append([event_id, user_id, session_id, event_time, event_type, product_id, category, price, device, location])
        event_id += 1

df = pd.DataFrame(data, columns=["event_id", "user_id", "session_id", "event_time", "event_type", "product_id", "category", "price", "device", "location"])
df

df.to_csv(r"/content/sample_data/generated_e_commerce_data.csv")